kind: ConfigMap
apiVersion: v1
metadata:
  name: collections
data:
  collections.json: |-
    [
      {"name":"none","display_name":"None"},
      {"name":"documents","display_name":"Evaluación Impacto Ambiental"}
    ]